# Form implementation generated from reading ui file 'APP\forms\forms_ui\category_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CategoryWindow(object):
    def setupUi(self, CategoryWindow):
        CategoryWindow.setObjectName("CategoryWindow")
        CategoryWindow.resize(445, 341)
        CategoryWindow.setStyleSheet("background-color: rgb(235, 231, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=CategoryWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.name_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_input.sizePolicy().hasHeightForWidth())
        self.name_input.setSizePolicy(sizePolicy)
        self.name_input.setMinimumSize(QtCore.QSize(0, 0))
        self.name_input.setMouseTracking(True)
        self.name_input.setTabletTracking(False)
        self.name_input.setAcceptDrops(True)
        self.name_input.setAutoFillBackground(False)
        self.name_input.setStyleSheet("background-color: rgb(235, 235, 245);\n"
"border-radius: 5px;\n"
"border: 1px solid dlack")
        self.name_input.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.name_input.setInputMask("")
        self.name_input.setText("")
        self.name_input.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.name_input.setDragEnabled(False)
        self.name_input.setReadOnly(False)
        self.name_input.setPlaceholderText("")
        self.name_input.setClearButtonEnabled(False)
        self.name_input.setObjectName("name_input")
        self.horizontalLayout_6.addWidget(self.name_input)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.table_data = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.table_data.setMinimumSize(QtCore.QSize(0, 0))
        self.table_data.setStyleSheet("background-color: rgb(253, 253, 255);\n"
"border-radius: 5px;\n"
"border: 1px solid dlack\n"
"")
        self.table_data.setObjectName("table_data")
        self.table_data.setColumnCount(0)
        self.table_data.setRowCount(0)
        self.table_data.horizontalHeader().setSortIndicatorShown(True)
        self.table_data.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.table_data)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.create_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.create_btn.setMinimumSize(QtCore.QSize(100, 0))
        self.create_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(185, 196, 255);\n"
"    padding: 5 10 5 10;\n"
"    border:1px solid black;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(155, 155, 224);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(140, 140, 207);\n"
"}")
        self.create_btn.setObjectName("create_btn")
        self.horizontalLayout_7.addWidget(self.create_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.clousing_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.clousing_btn.setMinimumSize(QtCore.QSize(100, 0))
        self.clousing_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(217, 74, 74);\n"
"    padding: 5 10 5 10;\n"
"    border:1px solid black;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(222, 87, 87);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(217, 139, 139);\n"
"}")
        self.clousing_btn.setObjectName("clousing_btn")
        self.horizontalLayout_7.addWidget(self.clousing_btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        CategoryWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(CategoryWindow)
        QtCore.QMetaObject.connectSlotsByName(CategoryWindow)

    def retranslateUi(self, CategoryWindow):
        _translate = QtCore.QCoreApplication.translate
        CategoryWindow.setWindowTitle(_translate("CategoryWindow", "MainWindow"))
        self.label_6.setText(_translate("CategoryWindow", "Название:"))
        self.create_btn.setText(_translate("CategoryWindow", "Создать"))
        self.clousing_btn.setText(_translate("CategoryWindow", "Отмена"))
