from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(223, 120)
        LoginWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Triangular)
        self.centralwidget = QtWidgets.QWidget(parent=LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.login = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.login.setAutoFillBackground(False)
        self.login.setText("")
        self.login.setDragEnabled(False)
        self.login.setReadOnly(False)
        self.login.setClearButtonEnabled(False)
        self.login.setObjectName("login")
        self.verticalLayout.addWidget(self.login)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.password.setMouseTracking(True)
        self.password.setTabletTracking(False)
        self.password.setAcceptDrops(True)
        self.password.setAutoFillBackground(False)
        self.password.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.password.setInputMask("")
        self.password.setText("")
        self.password.setDragEnabled(False)
        self.password.setReadOnly(False)
        self.password.setClearButtonEnabled(False)
        self.password.setObjectName("password")
        self.verticalLayout.addWidget(self.password)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.login_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.login_btn.setStyleSheet("background-color: rgb(166, 255, 164);")
        self.login_btn.setObjectName("login_btn")
        self.horizontalLayout.addWidget(self.login_btn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.registrate_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.registrate_btn.setStyleSheet("background-color: rgb(169, 213, 255);")
        self.registrate_btn.setObjectName("registrate_btn")
        self.horizontalLayout.addWidget(self.registrate_btn)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)
        LoginWindow.setTabOrder(self.login, self.password)
        LoginWindow.setTabOrder(self.password, self.login_btn)
        LoginWindow.setTabOrder(self.login_btn, self.registrate_btn)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.login.setPlaceholderText(_translate("LoginWindow", "Логин"))
        self.password.setPlaceholderText(_translate("LoginWindow", "Пароль"))
        self.login_btn.setText(_translate("LoginWindow", "Вход"))
        self.registrate_btn.setText(_translate("LoginWindow", "Регистрация"))
