# Form implementation generated from reading ui file 'APP\forms\forms_ui\create_product_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CreateProductWindow(object):
    def setupUi(self, CreateProductWindow):
        CreateProductWindow.setObjectName("CreateProductWindow")
        CreateProductWindow.resize(513, 110)
        CreateProductWindow.setStyleSheet("background-color: rgb(235, 231, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=CreateProductWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.name_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.name_line.setMinimumSize(QtCore.QSize(300, 0))
        self.name_line.setStyleSheet("background-color: rgb(235, 235, 245);\n"
"border-radius: 5px;\n"
"border: 1px solid dlack")
        self.name_line.setText("")
        self.name_line.setObjectName("name_line")
        self.horizontalLayout_2.addWidget(self.name_line)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.quantitytBox = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.quantitytBox.setMinimumSize(QtCore.QSize(46, 0))
        self.quantitytBox.setStyleSheet("background-color: rgb(235, 235, 245);\n"
"border-radius: 5px;\n"
"border: 1px solid dlack")
        self.quantitytBox.setObjectName("quantitytBox")
        self.horizontalLayout.addWidget(self.quantitytBox)
        self.horizontalLayout_7.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.sizeBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.sizeBox.setMinimumSize(QtCore.QSize(60, 0))
        self.sizeBox.setStyleSheet("background-color: rgb(235, 235, 245);\n"
"border-radius: 5px;\n"
"border: 1px solid dlack")
        self.sizeBox.setObjectName("sizeBox")
        self.sizeBox.addItem("")
        self.sizeBox.setItemText(0, "")
        self.horizontalLayout_5.addWidget(self.sizeBox)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.categoriesBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.categoriesBox.setMinimumSize(QtCore.QSize(112, 0))
        self.categoriesBox.setStyleSheet("background-color: rgb(235, 235, 245);\n"
"border-radius: 5px;\n"
"border: 1px solid dlack")
        self.categoriesBox.setObjectName("categoriesBox")
        self.categoriesBox.addItem("")
        self.categoriesBox.setItemText(0, "")
        self.horizontalLayout_4.addWidget(self.categoriesBox)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.price_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.price_line.setStyleSheet("background-color: rgb(235, 235, 245);\n"
"border-radius: 5px;\n"
"border: 1px solid dlack")
        self.price_line.setObjectName("price_line")
        self.horizontalLayout_3.addWidget(self.price_line)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.create_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.create_btn.setMinimumSize(QtCore.QSize(100, 0))
        self.create_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(185, 196, 255);\n"
"    padding: 5 10 5 10;\n"
"    border:1px solid black;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(155, 155, 224);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(140, 140, 207);\n"
"}")
        self.create_btn.setText("")
        self.create_btn.setObjectName("create_btn")
        self.horizontalLayout_6.addWidget(self.create_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.clousing_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.clousing_btn.setMinimumSize(QtCore.QSize(100, 0))
        self.clousing_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(217, 74, 74);\n"
"    padding: 5 10 5 10;\n"
"    border:1px solid black;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(222, 87, 87);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(217, 139, 139);\n"
"}")
        self.clousing_btn.setObjectName("clousing_btn")
        self.horizontalLayout_6.addWidget(self.clousing_btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        CreateProductWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(CreateProductWindow)
        QtCore.QMetaObject.connectSlotsByName(CreateProductWindow)

    def retranslateUi(self, CreateProductWindow):
        _translate = QtCore.QCoreApplication.translate
        CreateProductWindow.setWindowTitle(_translate("CreateProductWindow", "MainWindow"))
        self.label.setText(_translate("CreateProductWindow", "Название:"))
        self.label_5.setText(_translate("CreateProductWindow", "Количество:"))
        self.label_2.setText(_translate("CreateProductWindow", "Размер:"))
        self.label_3.setText(_translate("CreateProductWindow", "Категория:"))
        self.label_4.setText(_translate("CreateProductWindow", "Цена:"))
        self.clousing_btn.setText(_translate("CreateProductWindow", "Отмена"))
